
# Development configuration

export PIPSI_HOME=$VIRTUALENVS_ROOT

if command -v pyenv &>/dev/null; then
    export PYENV_ROOT=$HOME/.local/pyenv
    export PYENV_VIRTUALENV_DISABLE_PROMPT=1

    if command -v pyenv-virtualenv-init &>/dev/null; then
        PYENV_VIRTUALENV_INIT=$(whence pyenv-virtualenv-init)
    fi
fi

export NODE_ENV=development

# Development path

path=($HOME/.local/bin $path)  # pipsi

# vim: ft=zsh

