
format = """
$username\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_status\
$git_state\
$fill\
$cmd_duration\
$nodejs\
$terraform\
$python\
$scala\
$java\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character
"""

[character]
success_symbol = '[❯](bright-yellow)'

[cmd_duration]
format = '[took](bold-black) [$duration]($style) '
style = 'blue'

[directory]
style = 'blue'
before_repo_root_style = 'bright-black'
repo_root_style = 'blue'
truncate_to_repo = false

[fill]
symbol = ' '

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[git_commit]
format = '[ $hash$tag]($style) '
style = 'purple'

[git_status]
format = '[($modified )($untracked )($ahead_behind )]($style)'
style = 'bright-black'
modified = '󰲶'
untracked = '󱗿'
diverged = '󰡎'
ahead = '󰞘'
behind = '󰞗'

[git_state]
format = '[$state( $progress_current/$progress_total)]($style) '
style = 'bright-black'

[gcloud]
format = '[($symbol $region$project )]($style)'
symbol = '󱇶'

[java]
detect_extensions = ['java', 'class', 'gradle']
format = '[via](bright-black) [$symbol ($version )]($style)'
style = 'red'
symbol = ''

[jobs]
symbol = ' '
style = 'bright-black'

[nodejs]
format = '[$symbol ($version )]($style)'
symbol = ''

[python]
format = '[$symbol $pyenv_prefix($version )(\($virtualenv\) )]($style)'
style = 'green'
symbol = '󰌠'

[scala]
format = '[$symbol ]($style)'
symbol = ''

[shlvl]
format = '[$symbol $shlvl ]($style)'
style = 'bright-yellow'
symbol = ''
threshold = 3
disabled = false

[terraform]
format = '[$symbol $version ]($style)'
style = 'purple'
symbol = ''

# TODO
# go
# gradle
# helm
# docker_context
# kubernetes
# memory
# package

